const fakePrescriptions = [
  {
    id: 1,
    name: 'Amoxicillin',
    dosage: '500mg',
    frequency: 'Every 8 hours',
    duration: '2',
    dateAdded: '2024-03-05',
    expanded: false,
    compatible: 'yes',
  },
  {
    id: 2,
    name: 'Ibuprofen',
    dosage: '200mg',
    frequency: 'Every 4 to 6 hours',
    duration: 'As needed',
    dateAdded: '2024-03-04',
    expanded: false,
    compatible: 'yes',
  },
  {
    id: 3,
    name: 'Metformin',
    dosage: '1000mg',
    frequency: 'Twice a day',
    duration: 'Ongoing',
    dateAdded: '2024-02-28',
    expanded: false,
    compatible: 'yes',
  },
  {
    id: 4,
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once a day',
    duration: 'Ongoing',
    dateAdded: '2024-03-01',
    expanded: false,
    compatible: 'yes',
  },
  {
    id: 5,
    name: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once a day',
    duration: 'Ongoing',
    dateAdded: '2024-03-03',
    expanded: false,
    compatible: 'yes',
  },
  {
    id: 6,
    name: 'Levothyroxine',
    dosage: '50mcg',
    frequency: 'Once a day in the morning',
    duration: 'Ongoing',
    dateAdded: '2024-03-02',
    expanded: false,
    compatible: 'yes',
  }
];

export default fakePrescriptions;